language: go

before_install:
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr
    - gox -build-toolchain

after_success:
    - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" github.com/rubenv/dupefinder/bin/dupefinder
    - ghr --username rubenv --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
